### PR TITLE
Modernize Distribution

### PR DESCRIPTION
**Pull request by curran**
This PR takes a first stab at #8 by:
 * Adopting Rollup in place of the Makefile
 * Modifying the source files to use ES6 modules
 * Setting up three distribution files (`main`, `browser`, and `module`), as per the canonical example in https://github.com/rollup/rollup-starter-lib/blob/master/package.json#L4
 * Ensuring the tests pass using the CommonJS distribution.

### CODE REVIEW

**Comment by curran** [comment]
Current status:
 * One file has been migrated, `adjacent_exchange.js`.
 * The export from this one file appears in the distribution.
 
Remaining work:
 * Migrate all other files.
 * Deal with the funky assignment of dependencies to globals seen in `src/aliases.js` (we should import from the `science` package - a general search & replace on `reorder.dot`, `reorder.length`, `reorder.length`, and `reorder.zeroes` should do the trick I think).
 * Make the tests pass again.
 *Double check that all the fields in `package.json` make sense (e.g. `unpkg` and `jsdelivr` fields).

**Comment by curran** [comment]
**Note:** `src/bfs_order.js` assigns a new global, `bfs_order`. It does not assign a value to the `reorder` global like the other modules.

This looks like a mistake?

Should this function even be part of the library? It appears it is not possible to use it unless you are looking for that `bfs_order` global, and it does not seem to be used anywhere.

**Comment by curran** [comment]
In the migration work I'm doing now, I could expose `bfs_order` from the library. That may have been the original intention?

When I look at https://observablehq.com/@fil/hello-reorder-js by @Fil , I see there is no BFS order. It could be added there with some additional modification of the import to also extract the global `bfs_order`.

image

**Comment by curran** [comment]
It seems a bit redundant to export the same thing with two different names here?

```
reorder.ca_decorana = decorana;
reorder.ca = decorana;
```

Keeping it as-is for now, maybe we can clean this up in future.

**Comment by curran** [comment]
In `core.js`, we could derive the version from `package.json`. That way there would be a single source of truth.

It could be done like this:
```js
import pkg from "../package.json";
export const version = pkg.version;
export const debug = false;
```

However, since this requires an additional Rollup plugin to get working, I think I'll leave it as-is (hardcoded). We can maybe revisit this later.

**Comment by curran** [comment]
Another case of seemingly not useful duplicate aliases:

```js
reorder.graph_random = reorder.graph_random_erdos_renyi;
```

**Comment by curran** [comment]
Whoah what is the story behind `src/hcluster.js`?

```js
science.stats.hcluster = function() { 
```

It's monkey patching the `science` package, overriding the existing implementation of `hcluster` from science.js, which can be found here https://github.com/jasondavies/science.js/blob/master/src/stats/hcluster.js

I wonder, why was this new version of `hcluster` introduced?

Here's the [diff between the original and the implementation here](https://github.com/jasondavies/science.js/compare/master...curran:patch-1).

Aha! I think this is the main difference:

```js
id: id++, //[jdf] keep track of original data index
```

I think I'll move ahead with approach of exposing `hcluster` on `reorder` itself, rather than monkey patching `science`, and changing references to it so that they use the local module.

**Comment by curran** [comment]
I need to stop for now but just to leave a note here on current status and the workflow:

 * I've been going through the list of source files alphabedically, and for each one migrating to use `export` wherever there are assignments to the `reorder` global, and adding those to the exports in `index.js`.
 * I'm up to `graph_random.js` so far.
 * After completing this first pass through all the source files, I plan to go through and replace all references to the `reorder` global with the appropriate imports from other source files. This is the second pass, as it depends on all the exports first being in place.
 * After doing that, the next task would be to revive the tests.
 * After that, we'd be in a position to publish a new version to NPM that uses the modernized distribution structure.
 * After that, I'd be keen to run Prettier over the codebase, and migrate internals to ES6 (`let`, `const`, and arrow function expressions).

Overall, this task seems doable with another push.

**Comment by curran** [comment]
This file appears to not be used anywhere: `src/intersect.js`.

I'll include it in the exports, though, as it might be useful? Another thing we can circle back to later and possibly delete if it's not required.

**Comment by curran** [comment]
Another alias that might be deletable `reorder.permutation = reorder.range`.

**Comment by curran** [comment]
I'll just call this `permute` internally, as `permute_copy` is not used anywhere:

```
reorder.permute = permute_copy;
```

**Comment by curran** [comment]
Noting that there are inconsistencies in naming: `transposeSlice` vs. `spectral_order`.

**Comment by curran** [comment]
`check_distance_matrix` appears not to be used anywhere.

Including for now, but we may want to delete this in future.

**Comment by curran** [comment]
Same with `fix_distance_matrix`.

**Comment by curran** [comment]
Status: Phase I is complete (exports).

Phase II is beginning (replace all `reorder.*` with the appropriate imports).

**Comment by curran** [comment]
I notice a reference error:

```
else if (p >= 1)
  return reorder.graph_complete(n, directed);
```

There was never such a thing as `reorder.graph_complete`. It should have been `reorder.complete_graph`.

**Comment by curran** [comment]
Status: Phase II complete. 

Last remaining tasks:
 * Make sure tests still pass.
 * Proofread `package.json`

**Comment by curran** [comment]
Ready for review @jdfekete @Fil. Thanks!

**Comment by Fil** [comment]
Fantastic work!

I've tried to use it on Observable but, so far, it seems to be stuck with `science` not being in the proper umd format: https://observablehq.com/d/cdde6496d7f1fdee

Another remark is that there should probably be a build step in `pretest`.

**Comment by Fil** [comment]
you might also want to update science.js to 1.9.3

**Comment by jdfekete** [comment]
Not sure how to address the problem of science not being in the proper umd format. I have updated science.js to 1.9.3 and it passes the tests.

**Comment by curran** [comment]
Created a new issue for tracking the `science` UMD issue https://github.com/jdfekete/reorder.js/issues/12

**Pull request merged**
