### PR TITLE
Manual es6 cleanup

### LINKED ISSUE #19: Refresh the code
@curran wrote: Another adjacent thought - if we were to really deeply refresh this library, we could also take a stylistic pass over the codebase and adopt let and const, and arrow function expressions. Also Prettier for code formatting would probably be a good move.

### PR DESCRIPTION
**Pull request by curran**
Closes #19

### CODE REVIEW

**Comment by curran** [comment]
Whoah there was an assignment to a global

```js
barycenter_sort = (a, b) => { 
```

**Comment by curran** [comment]
Probably more cleanup opportunity in Decorana. Did what I could with that code. It's pretty interesting that it's ported from old Fortran code.

**Comment by curran** [comment]
Ready for review @jdfekete @Fil. Thanks!

**Comment by jdfekete** [comment]
Thanks a lot for the cleanup. I fixed a few issues but everything seems to be fine. More tests are needed to be sure, but that'll be for later.

**Pull request merged**
